### ISSUE TITLE
Maybe some bugs for CIFAR100

### ISSUE THREAD

**Issue by jinly0513** [NeuralCollapseApplications/FSCIL#5]
Thank you for your impressive work. When I was trying to reproduce the result with two or three GPUs, even if the cofigs had been changed, CIFAR100 still produced a strange result that was unreasonable while the other two is normal. So I'm wondering if there are subtle bugs in CIFAR100 training especially in the evaluation process. Otherwise, the acc won't decrease dramatically after session2.
Here are the logs.
[cifar.log](https://github.com/NeuralCollapseApplications/FSCIL/files/11691020/cifar.log)
[cub.log](https://github.com/NeuralCollapseApplications/FSCIL/files/11691021/cub.log)
[imagenet.log](https://github.com/NeuralCollapseApplications/FSCIL/files/11691022/imagenet.log)

**Comment by HarborYuan** [comment]
Hi @17231041 ,

I want to first thank you for the interest in our work.

Did you adjust the batchsize for the incremenal sessions? You may need to adjust it here:
> https://github.com/NeuralCollapseApplications/FSCIL/blob/f89a4ef2faf0208247758d49b00843e993a3b975/mmfscil/apis/fscil.py#L552

If you use 2 gpus for incremental training, you may need to quadruple (x4) the batchsize.

But the final results will still be slightly different since the subtle implementation difference inside the PyTorch.

Regards,
HarborYuan

**Comment by HarborYuan** [comment]
Hi @jinly0513 ,

I would like to close the issue first, feel free to re-open it or raise a new one if you have any other question.

By the way, this issue is similar to #3 , which has been reported as resolved.

Thanks again for your interests.

Regards,
HarborYuan
